include: package:flutter_lints/flutter.yaml

linter:
  # Instead of disabling a lint rule for the entire project,
  # it can also be suppressed for a single line of code
  # `// ignore: name_of_lint` and
  # or a file
  # `// ignore_for_file: name_of_lint`
  rules:
    prefer_single_quotes: true
  
